version: 2
workflows:
  version: 2
  testing:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/php:7.2-fpm

    working_directory: ~/repo
    steps:
      - run:
          name: "Install composer"
          command: |
            wget https://raw.githubusercontent.com/composer/getcomposer.org/bc6cbcd2c0fbc03c7ab87442b5f1fbc9407f0b9900bddc10d755bdc81bbe7b6e/web/installer -O - -q | php -- --quiet
            sudo mv ./composer.phar /usr/local/bin/composer
            sudo chmod +x /usr/local/bin/composer

      - checkout

      - restore_cache:
          keys:
          - composer-dev-v1-{{ checksum "composer.json" }}

      - run: composer install --classmap-authoritative

      - save_cache:
          paths:
            - ./vendor
          key: composer-dev-v1-{{ checksum "composer.json" }}

      - run: if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit; fi
      - run: if [ -f vendor/bin/pharmacist ]; then vendor/bin/pharmacist; fi
      - run: if [ -f vendor/bin/phpstan ]; then php -d memory_limit=4G vendor/bin/phpstan analyse -l 0 src $(if [ -f phpstan.neon ]; then echo "-c phpstan.neon"; fi); fi