parameters:
  api_key: ""
  api_secret: ""

services:
  client:
    class: Silktide\BrightLocalApi\Client
    arguments:
      - "@api"
      - "@batch.factory"

  batch.factory:
    class: Silktide\BrightLocalApi\BatchFactory
    arguments:
      - "@api"

  api:
    class: Silktide\BrightLocalApi\Api
    arguments:
      - "@guzzle.client"
      - "%api_key%"
      - "%api_secret%"

  confighelper:
      class: Silktide\BrightLocalApi\Data\DirectoryConfigHelper
      arguments:
        - "@dataloader"

  dataloader:
      class: Silktide\BrightLocalApi\Data\DataLoader

  guzzle.client:
    class: GuzzleHttp\Client